//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robotiq
{
    [Serializable]
    public class CModelCommandFeedback : Message
    {
        public const string k_RosMessageName = "robotiq_msgs/CModelCommand";
        public override string RosMessageName => k_RosMessageName;

        //  Feedback
        public double position;
        public bool activated;
        public bool stalled;
        public bool reached_goal;

        public CModelCommandFeedback()
        {
            this.position = 0.0;
            this.activated = false;
            this.stalled = false;
            this.reached_goal = false;
        }

        public CModelCommandFeedback(double position, bool activated, bool stalled, bool reached_goal)
        {
            this.position = position;
            this.activated = activated;
            this.stalled = stalled;
            this.reached_goal = reached_goal;
        }

        public static CModelCommandFeedback Deserialize(MessageDeserializer deserializer) => new CModelCommandFeedback(deserializer);

        private CModelCommandFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            deserializer.Read(out this.activated);
            deserializer.Read(out this.stalled);
            deserializer.Read(out this.reached_goal);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.activated);
            serializer.Write(this.stalled);
            serializer.Write(this.reached_goal);
        }

        public override string ToString()
        {
            return "CModelCommandFeedback: " +
            "\nposition: " + position.ToString() +
            "\nactivated: " + activated.ToString() +
            "\nstalled: " + stalled.ToString() +
            "\nreached_goal: " + reached_goal.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
