//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robotiq
{
    [Serializable]
    public class CModelCommandGoal : Message
    {
        public const string k_RosMessageName = "robotiq_msgs/CModelCommand";
        public override string RosMessageName => k_RosMessageName;

        //  Goal
        public double position;
        public double velocity;
        public double force;

        public CModelCommandGoal()
        {
            this.position = 0.0;
            this.velocity = 0.0;
            this.force = 0.0;
        }

        public CModelCommandGoal(double position, double velocity, double force)
        {
            this.position = position;
            this.velocity = velocity;
            this.force = force;
        }

        public static CModelCommandGoal Deserialize(MessageDeserializer deserializer) => new CModelCommandGoal(deserializer);

        private CModelCommandGoal(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position);
            deserializer.Read(out this.velocity);
            deserializer.Read(out this.force);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.velocity);
            serializer.Write(this.force);
        }

        public override string ToString()
        {
            return "CModelCommandGoal: " +
            "\nposition: " + position.ToString() +
            "\nvelocity: " + velocity.ToString() +
            "\nforce: " + force.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Goal);
        }
    }
}
