//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robotiq
{
    [Serializable]
    public class CModelStatusMsg : Message
    {
        public const string k_RosMessageName = "robotiq_msgs/CModelStatus";
        public override string RosMessageName => k_RosMessageName;

        public uint gACT;
        public uint gGTO;
        public uint gSTA;
        public uint gOBJ;
        public uint gFLT;
        public uint gPR;
        public uint gPO;
        public uint gCU;

        public CModelStatusMsg()
        {
            this.gACT = 0;
            this.gGTO = 0;
            this.gSTA = 0;
            this.gOBJ = 0;
            this.gFLT = 0;
            this.gPR = 0;
            this.gPO = 0;
            this.gCU = 0;
        }

        public CModelStatusMsg(uint gACT, uint gGTO, uint gSTA, uint gOBJ, uint gFLT, uint gPR, uint gPO, uint gCU)
        {
            this.gACT = gACT;
            this.gGTO = gGTO;
            this.gSTA = gSTA;
            this.gOBJ = gOBJ;
            this.gFLT = gFLT;
            this.gPR = gPR;
            this.gPO = gPO;
            this.gCU = gCU;
        }

        public static CModelStatusMsg Deserialize(MessageDeserializer deserializer) => new CModelStatusMsg(deserializer);

        private CModelStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.gACT);
            deserializer.Read(out this.gGTO);
            deserializer.Read(out this.gSTA);
            deserializer.Read(out this.gOBJ);
            deserializer.Read(out this.gFLT);
            deserializer.Read(out this.gPR);
            deserializer.Read(out this.gPO);
            deserializer.Read(out this.gCU);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.gACT);
            serializer.Write(this.gGTO);
            serializer.Write(this.gSTA);
            serializer.Write(this.gOBJ);
            serializer.Write(this.gFLT);
            serializer.Write(this.gPR);
            serializer.Write(this.gPO);
            serializer.Write(this.gCU);
        }

        public override string ToString()
        {
            return "CModelStatusMsg: " +
            "\ngACT: " + gACT.ToString() +
            "\ngGTO: " + gGTO.ToString() +
            "\ngSTA: " + gSTA.ToString() +
            "\ngOBJ: " + gOBJ.ToString() +
            "\ngFLT: " + gFLT.ToString() +
            "\ngPR: " + gPR.ToString() +
            "\ngPO: " + gPO.ToString() +
            "\ngCU: " + gCU.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
