//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robotiq
{
    [Serializable]
    public class CModelCommandMsg : Message
    {
        public const string k_RosMessageName = "robotiq_msgs/CModelCommand";
        public override string RosMessageName => k_RosMessageName;

        public uint rACT;
        public uint rGTO;
        public uint rATR;
        public uint rPR;
        public uint rSP;
        public uint rFR;

        public CModelCommandMsg()
        {
            this.rACT = 0;
            this.rGTO = 0;
            this.rATR = 0;
            this.rPR = 0;
            this.rSP = 0;
            this.rFR = 0;
        }

        public CModelCommandMsg(uint rACT, uint rGTO, uint rATR, uint rPR, uint rSP, uint rFR)
        {
            this.rACT = rACT;
            this.rGTO = rGTO;
            this.rATR = rATR;
            this.rPR = rPR;
            this.rSP = rSP;
            this.rFR = rFR;
        }

        public static CModelCommandMsg Deserialize(MessageDeserializer deserializer) => new CModelCommandMsg(deserializer);

        private CModelCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rACT);
            deserializer.Read(out this.rGTO);
            deserializer.Read(out this.rATR);
            deserializer.Read(out this.rPR);
            deserializer.Read(out this.rSP);
            deserializer.Read(out this.rFR);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rACT);
            serializer.Write(this.rGTO);
            serializer.Write(this.rATR);
            serializer.Write(this.rPR);
            serializer.Write(this.rSP);
            serializer.Write(this.rFR);
        }

        public override string ToString()
        {
            return "CModelCommandMsg: " +
            "\nrACT: " + rACT.ToString() +
            "\nrGTO: " + rGTO.ToString() +
            "\nrATR: " + rATR.ToString() +
            "\nrPR: " + rPR.ToString() +
            "\nrSP: " + rSP.ToString() +
            "\nrFR: " + rFR.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
