//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robotiq
{
    [Serializable]
    public class CommandMsg : Message
    {
        public const string k_RosMessageName = "robotiq_msgs/Command";
        public override string RosMessageName => k_RosMessageName;

        public long SAFE_MODE;
        public long MEASURE;
        public long MEASURE_INPUT;
        public long POSITION;
        public long VELOCITY;
        public long FORCE;

        public CommandMsg()
        {
            this.SAFE_MODE = 0;
            this.MEASURE = 0;
            this.MEASURE_INPUT = 0;
            this.POSITION = 0;
            this.VELOCITY = 0;
            this.FORCE = 0;
        }

        public CommandMsg(long SAFE_MODE, long MEASURE, long MEASURE_INPUT, long POSITION, long VELOCITY, long FORCE)
        {
            this.SAFE_MODE = SAFE_MODE;
            this.MEASURE = MEASURE;
            this.MEASURE_INPUT = MEASURE_INPUT;
            this.POSITION = POSITION;
            this.VELOCITY = VELOCITY;
            this.FORCE = FORCE;
        }

        public static CommandMsg Deserialize(MessageDeserializer deserializer) => new CommandMsg(deserializer);

        private CommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.SAFE_MODE);
            deserializer.Read(out this.MEASURE);
            deserializer.Read(out this.MEASURE_INPUT);
            deserializer.Read(out this.POSITION);
            deserializer.Read(out this.VELOCITY);
            deserializer.Read(out this.FORCE);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.SAFE_MODE);
            serializer.Write(this.MEASURE);
            serializer.Write(this.MEASURE_INPUT);
            serializer.Write(this.POSITION);
            serializer.Write(this.VELOCITY);
            serializer.Write(this.FORCE);
        }

        public override string ToString()
        {
            return "CommandMsg: " +
            "\nSAFE_MODE: " + SAFE_MODE.ToString() +
            "\nMEASURE: " + MEASURE.ToString() +
            "\nMEASURE_INPUT: " + MEASURE_INPUT.ToString() +
            "\nPOSITION: " + POSITION.ToString() +
            "\nVELOCITY: " + VELOCITY.ToString() +
            "\nFORCE: " + FORCE.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
